spring.application.name=employee_management_app
spring.datasource.url=jdbc:postgresql://localhost:5432/jawa_bd
spring.datasource.username=postgres
spring.datasource.password=Freedom83@
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Email properties
spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=freedoklenz@gmail.com
spring.mail.password=jsexqlzeerisaqjt
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.enable=true

admin.email=freedoklenz@gmail.com



server.port = 9000

#cloudinary
cloudinary.cloud-name=dkdmxvof3
cloudinary.api-key=118973387622113
cloudinary.api-secret=ywx2g3datU81cjWslTtn5QnHHM0


secret-key=MIHcAgEBBEIBalbNcwF1mb/0RLmXcY2tvVlYUzNAQEj7+SJVEOZm1fy/+LJcaM8ziKdyDF2GjlNjNll+ddfMf0qiyi0DXJiR8HKgBwYFK4EEACOhgYkDgYYABACjuzJ+k2yr5Uy+T9Wqi5NQ49nCkOb/8po6LmUD0g1QEoAQVDYBm7H8oVxqOqRQRdRfAvNyIBSp7exGBEaRDvpBxwBSv9N+liDQTecWCpssRDG9qED7TGtduV1AXPABiHMehOIqyVTxwTHzhUwyIpNEMI2+8IVC/7rmkiXb3YU+bfqamQ==

